apiVersion: v1
description: Helm Chart for Docker example-voting-app
name: example-voting-app
keywords:
- codefresh
- kubernetes
- example-voting-app
version: 1.0.0
sources:
- https://github.com/dwilliams-codefresh/example-voting-app
maintainers:
- name: Dustin Van Buskirk
  email: dustinvb@codefresh.io
- name: Daniel Williams
  email: dwilliams+codefresh@port8080.net
  
